apiVersion: v1
kind: Service
metadata:
  name: project-management-service
spec:
  selector:
    app: project-management-app
  ports:
    - name: project-service
      port: 5000
      targetPort: 5000
    - name: task-service
      port: 5001
      targetPort: 5001
    - name: collaboration-service
      port: 5002
      targetPort: 5002
    - name: integration-service
      port: 5003
      targetPort: 5003
  type: LoadBalancer